version: "3.8"

services:

  template-service:
    build: ./TemplateService
    image: muhammadmuzamil1/template-service:v3
    ports:
      - "8080:8080"
  
  document-service:
    build:  ./DocumentService
    image: muhammadmuzamil1/document-service:v3
    ports:
      - "8082:8082"

  draft-service:
    build: ./DraftService
    image: muhammadmuzamil1/draft-service:v3
    ports:
      - "8081:8081"
    depends_on:
      - template-service

  api-gateway-service:
    build: ./ApiGateway
    image: muhammadmuzamil1/api-gateway:v3
    ports:
      - "8083:8083"
    depends_on:
      - document-service
      - template-service

  frontend:
    build: ./Frontend
    image: muhammadmuzamil1/frontend:v7
    ports:
      - "5173:80"
