server:
  port: 8083

spring:
  profiles:
    active: local
  application:
    name: api-gateway-service

management:
  endpoints:
    web:
      exposure:
        include: health,gateway,circuitbreakers,circuitbreakerevents

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

    gateway:
      enabled: true

resilience4j:

  circuitbreaker:

    instances:

      templateService:

        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

      documentService:

        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true