server:
  port: 8083

spring:
  application:
    name: api-gateway-service

management:
  endpoints:
    web:
      exposure:
        include: health,gateway

  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

    gateway:
      enabled: true

